### ISSUE TITLE
Add restart button

### ISSUE THREAD

**Issue by yuvalavra** [bughuntrio/issues#2]
Add a restart button to the scenario/stage UI to restart the challenge VM. For cases when the terminal/VM crashes. Currently a workaround is to log out then and log in.

**Comment by ajxchapman** [comment]
Thanks for the feature request @YuvalAvra, this one is actually already in the backlog for this week bughuntrio/frontend#38 (although it may get pushed back to next week).

I'll update this issue when the feature has been release.

Cheers

**Comment by ajxchapman** [comment]
This has now been deployed, if you notice any problems please let us know.

Enjoy!

**Comment by yuvalavra** [comment]
Thanks! works great on my end. 

Very minor UI issue - the reboot tooltip escapes the screen (chrome)
![image](https://user-images.githubusercontent.com/39744677/139879646-a5c44dcc-ac2c-4248-a49d-798cd1a7184b.png)
